# version: '3'

# networks:
#   bridge:
#     driver: bridge

# services:
#   redis:
#     image: "redis:latest"
#     ports:
#       - "6379:6379"
#     networks:
#       - bridge

#   celery_worker:
#     build: .
#     command: celery -A your_project_name worker --loglevel=info
#     volumes:
#       - .:/app
#     depends_on:
#       - redis
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#     networks:
#       - bridge

#   your_app:
#     build: .
#     volumes:
#       - .:/app
#     depends_on:
#       - celery_worker
#       - redis
#     networks:
#       - bridge
