apiVersion: v1
kind: Secret
metadata:
  name: mapbox-secret
type: Opaque
data:
  MAPBOX_ACCESS_TOKEN: cGsuZXlKMUlqb2lhWFpoYm5SdmJTSXNJbUVpT2lKamJESm1lbTVuYjIwd1kzVm9NMnR5ZW5Oa1ozRnViVFp3SW4wLlRnbnN2aHgzRmtOb0JIMVhJQktweFE=
  