name: Build and Publish Account Service Docker Image
on:
  push:
    branches:
      - master
      - main

jobs:
  build-user_and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          cd user_service && docker build . --tag user:latest
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to Github Container Registry
        run: |
          docker tag user:latest ghcr.io/tomdieu/disasterflow/user:latest
          docker push ghcr.io/tomdieu/disasterflow/user:latest

  build-alerts-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          cd alert_service && docker build . --tag alert:latest
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to Github Container Registry
        run: |
          docker tag alert:latest ghcr.io/tomdieu/disasterflow/alert:latest
          docker push ghcr.io/tomdieu/disasterflow/alert:latest
          
  build-emergency_responder-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          cd emergency_responder_service && docker build . --tag emergency_responder:latest
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to Github Container Registry
        run: |
          docker tag emergency_responder:latest ghcr.io/tomdieu/disasterflow/emergency_responder:latest
          docker push ghcr.io/tomdieu/disasterflow/emergency_responder:latest